@echo off
echo "hello world"
echo "                                 MMMMMM=                                    "  
echo "                         .MMMMMMMMMMMMMM                                   "
echo "                        MMMMMM         MMMM                                 "
echo "                     MMMMM              MMMMM.                              "
echo "               MMMMMMMM                  ?MMMM.                             "
echo "            .MMMMMMMM7MM                  MMMMM                             "
echo "             MMMMMMMMM MM                   MMMM                             "
echo "             MMMMMMMMM .MM                   MMM                             "
echo "            .MMMMMMM.   MM.M.   =MMMMMMMM.   MMM                             "
echo "             MMMMMMMM.MMMMMM.  MMMMMMMM MMM  MMM                             "
echo "             MMMMMMMMMMMM     MMMMMMMMM  MMM MMM                             "
echo "            MMM    MMM:  MM   MMMMMMMMM  MMM MMM                             "
echo "           8MM.    MMMMMMMM=  MMMMMMMM.  .M ,MM7                             "
echo "          MMMMMMMM..          MMMMM.     M  MMM                              "
echo "         .MMMMMMMMMMMMMMM       MMMMMMMMM.  MMM                              "
echo "        .MMM        MMMMMMMMMMM.           MMMM                              "
echo "        MMM                .~MMMMMMM.      MMM.                              "
echo "       MMM.                               MMMM                               "
echo "      .MMM                                MMMM                               "
echo "      MMM                                DMMM                                "
echo "     MMM                                 MMMM                                "
echo "     MMM                                .MMM                                 "
echo "    MMM                      MM        .MMM                                  "
echo "    MMM                     .MM  MM.   MMM~                                  "
echo "    MMM                     MMM .MM.   MMM                         MMMMM     "
echo "    MMM                     MM. MMM   MMM                        MMM   MMO   "
echo "    MMM                     MM  MM   .MMM                      MMMM     MM   "
echo "    MM~                    MM. MMM   MMM.                     MMM      IMM   "
echo "    MM.                    MM  MM.  .MMM                    .MMM.      MM    "
echo "    MM                     M  MMN   .MMM                   MMMM       MM.    "
echo "    MM+                   MM MMM    .MM 7MMMMMMMMMMM      MMM.       MM      "
echo "    MMM                  .M  MM      MMMMMM. .. MMMMMMM MMM.       MMM.      "
echo "    MMM                  +M MMM      MM    .MM     .MMMMMM.      .MMM.       "
echo "    ?MM                  M  MM       .      MMM      ~MM.       MMMM         "
echo "    .MM                 MM  MM            ,MMMMMMMMMMM         MMMM          "
echo "     MMM              MM     MM          MMMMMMMMMMMMMMM     MMMMM           "
echo "     MMM            .M     N  MM                  ..MMMMM.     MMMM          "
echo "     .MM             MMMM MMMMMM                     .MMMMM        DMM       "
echo "      MMM              MMMMM.MM.             ,M,       .MMM.        MM       "
echo "       MMM               M.                  MMM         MMM.  .MMMM         "
echo "       MMMM                                              MMM.    MM          "
echo "        =MMM.                            MM.             MMM      MM         "
echo "          MMMM.                          MM              MMM       M         "
echo "            MMMM                                         MMMMM,. MMM         "
echo " .          MMMMMMM.                     MMM            MMM MMMMMM.          "
echo " MMMM      MMN  .MMMMM                               .MMMD                   "
echo " MM MMN  .MM    MM MMMMMMMM~ .              M.     .MMMM                     "
echo " MM   MM$MM   MMN      MMMMMMMMMM.          M.   .MMMM                       "
echo "  M.   MMM   MM              MMMMM  MMMMMMMMM~MMMMMM                         "
echo "  MM      .MMN          .. . +MM,  8MM .MMMMMMMM.                            "
echo "   M?    NMM           MMMMMMMMM   MM                                        "
echo "   .M  .MM7            MMM MMMM   MM                                         "
echo "     MMMM              OMM       .MM                                         "
echo "      .                 MMM      MM                                          "
echo "                        .MMM    MM                                           "
echo "                         .MMD  MMM                                           "
echo "                           MMMMM?                                            "
echo "                            MMM.        "
echo " "
test > test.txt